name: Check for 'do not merge' label

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  allow-merge:
    name: Allow Merge
    runs-on: ubuntu-latest
    env:
      should_block: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
    steps:
      - name: Check for label
        run: |
          if [[ "$should_block" = "true" ]]; then
            exit 1
          else
            exit 0
          fi
